[package]
name = "aftermath_adapter"
version = "0.0.1"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir="crates/sui-framework/packages/sui-framework/", rev = "testnet" }
SuiSystem = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-system", rev = "testnet" }
WispLSDFi = { local = "../../lsdfi" }
WispLSDFIAggregator = { local = "../../aggregator"}
aftermath = { local = "../../protocols/aftermath-interface" }

[addresses]
aftermath_adapter =  "0x0"
sui = "0x2"

