[package]
name = "aftermath"
version = "0.0.1"
published-at = "0x58e6bdd081ae6035141871a1c7cdf82895e944a8b7673f78d22e370a07cbf99b"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "testnet" }
afsui = { local = "../afsui" }
afsui_referral = { local = "../afsui-referral" }


[addresses]
aftermath = "0x58e6bdd081ae6035141871a1c7cdf82895e944a8b7673f78d22e370a07cbf99b"
sui = "0x2"

