[package]
name = "StWISP"
version = "0.0.1"
published-at = "0x10b80f93b1cafe10cf912dd2d15fa156114e6ab33eb80152a099f8514a9863f6"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir="crates/sui-framework/packages/sui-framework/", rev = "testnet" }

[addresses]
stwisp =  "0x10b80f93b1cafe10cf912dd2d15fa156114e6ab33eb80152a099f8514a9863f6"
sui = "0x2"