[package]
name = "WispLSDFIAggregator"
version = "1.0.0"
published-at = "0xcbb27865df487acdffb16f770409aa83d97e8189f5855e29247cc4d574a201e6"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir="crates/sui-framework/packages/sui-framework/", rev = "testnet" }

[addresses]
wisp_lsdfi_aggregator = "0xcbb27865df487acdffb16f770409aa83d97e8189f5855e29247cc4d574a201e6"
sui = "0x2"